### PR TITLE
Refactor Providers Controller to remove duplication of current_provider

### LINKED ISSUE #31: Refactor app/controllers/providers_controller.rb (good for new project member)
Eliminate following duplicate code in app/controllers/providers_controller.rb, which is giving the file a 'D' in Code Climate:
current_provider=Provider.find(session[:provider_id])

### PR DESCRIPTION
**Pull request by sic-f**
Refactor ProvidersController to dry out current_provider.
fixes #31

### CODE REVIEW

**Comment by mattlindsey** [comment]
Looks fine, but does it make sense to also update the other places in this PR where you note:
   #can also replace this with current_provider, but must update as well in the views

That would be nice.

**Comment by sic-f** [comment]
Ok will do. Thanks.

**Comment by sic-f** [comment]
@mattlindsey Hi Matt. I think I'm done with this now. Although in my tests I used render_views to match the provider name string in the views. 

I heard somewhere using render_views is discouraged because it slows down tests. I was thinking maybe this kind of test is done in cucumber? Thanks.

**Comment by mattlindsey** [comment]
@sic-f  Hi. I'll merge this because it seems fine.  You or I can open a ticket to do the test in cucumber if you want.  Thanks!

**Pull request merged**
