### PR TITLE
Model valdiations added to RedeemifyCode and VendorCode; fixes #71

### LINKED ISSUE #71: Tables allow code duplicates (PT#137856501)
2 bugs of the same nature are related to the Vendor#import method, i.e. the VendorCode and RedeemifyCode models may have multiple instances of the same code value. There is neither value validation for both models, nor verification for the existing value when creating new instances in the import method.

Suggest creating rspec or cucumber test for this bug, and fix using TDD/BDD.

### PR DESCRIPTION
**Pull request by Uzzsen**
Updates in brief:

- feature scenarios added to demo the issues in provider_upload_codes.feature and vendor_upload_codes.feature;
- related controller and model specs updated for additional examples;
- RedeemifyCode and VendorCode validations include value uniqueness and length (255 charactes) constraints for the code attribute;
- related provider and vendor work flows have been rethought prompting modifications in the provider and vendor controllers (#import, #import2 actions);
- user is notified of rejected codes via file download;
- Vendor.import has been modified to process violations of model constraints.

### CODE REVIEW

**Comment by alexander-kh** [comment]
Some notes on this task.
BDD assumes that we write scenarios to define the behavior of the app.
Consider scenario of rejecting of invalid codes in provider_upload_codes.feature
We can make it more simple and move all the details in step definitions.
For example, 

Scenario: Rejecting of invalid codes

    When I upload file with provider codes
    And some codes in the list are invalid
    Then invalid codes should not be uploaded

Also, there is a [convention](https://github.com/bbatsov/ruby-style-guide#snake-case-symbols-methods-vars) to use snake_case for the variable names.

Anyway, thank you! Good job!

**Comment by Uzzsen** [comment]
Alex, thanks for the review.

Good point on the snake_case naming for variables in compliance with the convention. However, personally I find a long string interspersed with spaces and underscores less parsable for comprehension compared to a composition with snake_case parts for variables and camelCase bits for variables. That said, the amending commit with snake_case naming for variables is forthcoming.

I'll also think about the appropriate step definitions for the suggested scenario to conceal the technical detail.

**Comment by Uzzsen** [comment]
Latest commit suggests code changes and additional scenario to account for empty file upload by both provider and vendor.

**Comment by alexander-kh** [comment]
Thank you! Good work!
We can continue improvements.

What do you think about adding validation on the file name, to allow only text files for uploading?
Next, let's consider how the file is handled.
It is processed by rows. One code it is all the characters in a row without spaces.
This assumes that codes in a file represented one per line.
In this case, there is no necessity in eliminating spaces.
```
row = row.gsub(/\s+/, "")
```
When codes are presented through delimiter, we have to split the line by space.
For example,
```
f.each_line do |row|
  codes = row.split(/\s+/)
  codes.each do |code|
    ...
  end
end
```
Also, what do you think about special characters in codes?
We can allow only letters and digits ([a-zA-Z0-9] or %r{\w} (with underscore))
And one more note: to display rejected codes in .txt-file one per line on Windows as well, we can add \r\n.

**Comment by Uzzsen** [comment]
Hi Alex,

The upcoming commit features 
- additional verification for the upload file format ('.txt') + cuke scenarios and specs;
- \r\n to encode the new line in a document opened in the Windows environment.

Space-delimited codes would seem a change in the requirements and should be approved by the product owner. Likewise, I would seek approval to exclude special characters from the codes.

**Pull request merged**
