### PR TITLE
add dev seed data

### PR DESCRIPTION
**Pull request by mattlindsey**
@armandofox This PR probably isn't quite ready.  I am having some difficulty understanding what to do next, but I think something like this is a good idea.  Could you review it and add comments/suggestions?

### CODE REVIEW

**Comment by mattlindsey** [comment]
This PR corresponds to Issue #10

**Comment by armandofox** [comment]
This is right direction.  I'd suggest though that in seeds.rb, just do something like
```ruby
raise "I refuse to destroy the production database!" if Rails.env.production?
```
which allows seeds to be run in test and dev but not production.
If the **tests** expect the seed data, we also have to do `load("db/seeds.rb)` in  the Rspec before-all block in `rails_helper.rb` or `spec_helper.rb`,  and probably `features/support/env.rb` in the Before block.
Can we get Travis CI set up on this repo so that pull requests are automatically CI'd before merged?
Thanks!!

**Comment by armandofox** [comment]
Is this PR obsolete?
I think it'd be OK to add seed data for a "test" provider, but not for real one(s).  I was going to approach Amazon to be a provider and get this thing off the ground...

**Comment by mattlindsey** [comment]
Obsolete. Closing.

**Pull request closed without merging**
