### PR TITLE
[WIP] 'Skinny' sessions_controller.rb (PT#135409281)

### PR DESCRIPTION
**Pull request by Uzzsen**
-  new redeemify_codes.serve and vendors#serve_code refactored to related models from sessions#customer + specs;

- skinnier sessions#customer: code flow redesigned and additional specs;

- template views updated for the current_vendor helper method + additional VendorsController specs;

- fixes wrong provider to update unclaimCodes and usedCodes in sessions#customer:56
  the issue is manifested through the updated user_login.feature, user_steps.rb and unchanged
  SessionsController;

- cursor hover behavior adjusted for the 'Download And Remove Unclaimed Codes' and 'Clear History'
  buttons on Provider Homepage; compliments #27 fix;

### CODE REVIEW

**Comment by Uzzsen** [comment]
Mat et al.,

Please review the proposed code updates and/or suggest further changes before the pull request is accepted.

**Comment by mattlindsey** [comment]
Hi.  I am finding it a little difficult to review this PR, since the changes are not in a branch that I can pull down.
Is it possible for you to create a branch from now on on your local, then push the branch to strawberrycanyon/redeemify, then create the PR from the branch?  Make sense?  Thanks. :)

If that is too hard to do at this point, let's do it going forward.

**Comment by Uzzsen** [comment]
Yes, Matt. However, when I tried to push the branch to strawberrycanyon/redeemify from my local, I encountered
"Permission to strawberrycanyon/redeemify.git denied to Uzzsen."

Instead I can push my local feature branch to my remote and then make a PR from my remote branch to strawberrycanyon/redeemify master. Will that do ?

If yes, what about the already created PR ?

**Comment by mattlindsey** [comment]
Hi @Uzzsen.  I made you a collaborator in the repo, so you can push your branch, create a new PR, and delete/close this one -- if that's OK.

**Pull request merged**
